#!/bin/sh

# Based on Casey Bisson's PHP based deploy script found here:
# https://github.com/misterbisson/bgeo/blob/master/deploy/push-to-wporg-repo.php

# Requirements: Git and SVN repo for your plugin/theme
# this script take one argument which is the plugin slug in the WordPress repository

if [ $1 ]; then
  SLUG=$1
else
  CURRENT_DIR_NAME=${PWD##*/}

  # convert camelcase directory to lower hyphen-case without spaces
  SLUG=$(echo $CURRENT_DIR_NAME | sed -e 's/\([A-Z]\)/-\L\1/g' -e 's/^-//' -e 's/ //g')
fi

SVN_REPO_PATH="/tmp/${SLUG}" #path to a temp SVN repo
SVN_REPO_URL="http://plugins.svn.wordpress.org/${SLUG}/trunk/"
SVN_IGNORE_FILES=".svnignore"
MESSAGE=$(git log -1 HEAD --pretty=format:%s)
CURRENT_DIR=${PWD%/*}


exit

echo "Preparing to push ${SLUG} to ${SVN_REPO_URL}"

echo 'Cleaning the destination path'
rm -Rf ${SVN_REPO_PATH}

echo "Creating local copy of SVN repo at ${SVN_REPO_PATH}"
svn checkout ${SVN_REPO_URL} ${SVN_REPO_PATH}

echo 'Prepping the SVN repo to receive the git'
rm -Rf ${SVN_REPO_PATH}/*

echo 'Exporting the HEAD of master from git to SVN'
git checkout-index -a -f --prefix=${SVN_REPO_PATH}/

echo 'Exporting git submodules to SVN'
git submodule foreach 'git checkout-index -a -f --prefix=${SVN_REPO_PATH}/\$path/'

echo 'Copying and reformatting README.md to readme.txt'
cat README.md | sed 's/^\#* //' > ${SVN_REPO_PATH}/readme.txt

echo 'Removing any svn:executable properties for security'
find ${SVN_REPO_PATH} -type f -not -iwholename *svn* -exec svn propdel svn:executable {} \; | grep 'deleted from'

echo 'Setting svn:ignore properties'
svn propset svn:ignore -F $SVN_IGNORE_FILES $SVN_REPO_PATH

svn proplist -v ${SVN_REPO_PATH}

echo 'Marking deleted files for removal from the SVN repo'
svn st ${SVN_REPO_PATH} | grep '^\!' | sed 's/\!\s*//g' | xargs svn rm

echo 'Marking new files for addition to the SVN repo';
svn st ${SVN_REPO_PATH} | grep '^\?' | sed 's/\?\s*//g' | xargs svn add

echo 'Now forcibly removing the files that are supposed to be ignored in the svn repo'

while read file; do
  svn rm --force ${SVN_REPO_PATH}/$file
done <"${SVN_REPO_PATH}/deploy/${SVN_IGNORE_FILES}"


echo "
//////////////////////////////////////////////////

Committing the changes to the WordPress repository

//////////////////////////////////////////////////
"

cd ${SVN_REPO_PATH}
svn commit -m "${MESSAGE}"
cd "${CURRENT_DIR}" # in quotes because maybe spaces in path


echo "
//////////////////////////////////////////////////
//////////////////////////////////////////////////
//////////////////////////////////////////////////

Deployment to WordPress Plugin repository complete

//////////////////////////////////////////////////
//////////////////////////////////////////////////
//////////////////////////////////////////////////
"
